server:
  shutdown: graceful

spring:
  datasource:
    url: jdbc:h2:mem:food;MODE=LEGACY;
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 1m

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG